DROP TABLE IF EXISTS users CASCADE;
-- ALTER SEQUENCE users_id_seq RESTART;
CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL
);
