DROP TABLE IF EXISTS ratings CASCADE;
-- ALTER SEQUENCE ratings_id_seq RESTART;
CREATE TABLE ratings (
  id SERIAL PRIMARY KEY NOT NULL,
  rating SMALLINT NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  resource_id INTEGER REFERENCES resources(id) ON DELETE CASCADE
);
